# Generated by Django 3.1 on 2020-12-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=1)),
                ('birthYear', models.CharField(max_length=6)),
                ('ringNumber', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=20)),
                ('mother', models.CharField(max_length=20)),
                ('thumb', models.ImageField(blank=True, default='defaultpigeon.jpg', upload_to='')),
            ],
        ),
    ]
