# Generated by Django 3.1 on 2020-12-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fancier', '0003_remove_fancier_birthdate'),
        ('pigeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='fancier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='fancier.fancier'),
        ),
    ]
