# Generated by Django 3.1 on 2020-12-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0002_pigeon_fancier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigeon',
            name='father',
        ),
        migrations.RemoveField(
            model_name='pigeon',
            name='mother',
        ),
    ]
