# Generated by Django 3.1 on 2020-12-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0004_pigeon_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigeon',
            name='father',
        ),
    ]
