# Generated by Django 3.1 on 2020-12-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0005_remove_pigeon_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pigeonFather', to='pigeon.pigeon'),
        ),
    ]
