# Generated by Django 3.1 on 2020-12-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0007_pigeon_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='father',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pigeonFather', to='pigeon.pigeon'),
        ),
    ]
