# Generated by Django 3.1 on 2020-12-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0012_auto_20201210_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='thumb',
            field=models.ImageField(blank=True, default='defaultpigeon.png', upload_to=''),
        ),
    ]
