# Generated by Django 3.1 on 2020-12-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0013_auto_20201210_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
