# Generated by Django 3.1 on 2020-12-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fancier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fancier',
            name='profilePicture',
            field=models.ImageField(blank=True, default='defaultfancier.png', upload_to=''),
        ),
    ]
