# Generated by Django 3.1 on 2020-12-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fancier', '0002_fancier_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fancier',
            name='birthDate',
        ),
    ]
